Cerad\Bundle\GameBundle\Entity\GameOfficial:
    type:  entity
    table: game_officials
    uniqueConstraints:
       game_official_game_slot_index:
           columns: gameId, slot

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
            
    manyToOne:
          
        game:
            targetEntity: Game
            inversedBy:   officials
            nullable:     false
            joinColumn:
                name:                 gameId
                referencedColumnName: id
      
    fields:
            
        slot:
            column:   slot
            type:     integer
            nullable: false
            
        role:
            column:   role
            type:     string
            length:   20
            nullable: false
            
        personNameFull:
            column:   personNameFull
            type:     string
            length:   80
            nullable: true
                
        state:
            column:   state
            type:     string
            length:   20
            nullable: true
            
        status:
            column:   status
            type:     string
            length:   20
            nullable: true


