Cerad\Bundle\GameBundle\Entity\Project:
    type:  entity
    table: projects
    repositoryClass: Cerad\Bundle\GameBundle\Entity\ProjectRepository
    changeTrackingPolicy: NOTIFY
    
    indexes:
       project_season_index:
           columns: season
       project_sport_index:
           columns: sport
       project_domain_index:
           columns: domain
       project_domain_sub_index:
           columns: domain_sub
        
    id:
        id:
            type: string
            length: 80
            generator: { strategy: NONE }
    
    fields:
        season:
            column:   season
            type:     string
            length:   20
            nullable: false
            indexed:    true
            
        sport:
            column:   sport
            type:     string
            length:   20
            nullable: false
            
        domain:
            column:   domain
            type:     string
            length:   20
            nullable: false
            
        domainSub:
            column:   domain_sub
            type:     string
            length:   20
            nullable: false
            
        status:
            column:   status
            type:     string
            length:   20
            nullable: true
