parameters:

    #cerad_project_project_default: AYSOS1GamesUpperFall2013
    #cerad_project_project_default: AYSOS1GamesLowerSpring2014
    
    cerad_project__project_files:
        - "%kernel.root_dir%/config/projects/ALYS_Classic_Spring2013.yml"
        