cerad_game_schedule:
    pattern:  /
    defaults: 
        _controller: CeradGameBundle:GameSchedule:index
        _template: '@CeradGame\Game\Schedule\GameScheduleIndex.html.twig'
    
cerad_game_schedule_import:
    pattern:  /import
    defaults: { _controller: CeradGameBundle:GameScheduleImport:import }
  
