services:

# =============================================================
# Project stuff

    cerad_project.entity_manager.doctrine:
        alias: doctrine.orm.default_entity_manager
        
    cerad_project.project_repository.doctrine:
        class:  Cerad\Bundle\GameBundle\Entity\ProjectRepository
        factory_service: 'cerad_project.entity_manager.doctrine'
        factory_method:  'getRepository'
        arguments:  
            - 'Cerad\Bundle\GameBundle\Entity\Project'
            
    cerad_project.project_repository:
        alias: cerad_project.project_repository.doctrine
        
# =============================================================
# Level stuff

    cerad_level.entity_manager.doctrine:
        alias: doctrine.orm.default_entity_manager
        
    cerad_level.level_repository.doctrine:
        class:  Cerad\Bundle\GameBundle\Entity\LevelRepository
        factory_service: 'cerad_level.entity_manager.doctrine'
        factory_method:  'getRepository'
        arguments:  
            - 'Cerad\Bundle\GameBundle\Entity\Level'
            
    cerad_level.level_repository:
        alias: cerad_level.level_repository.doctrine
        
# =============================================================
# Game stuff

    cerad_game.entity_manager.doctrine:
        alias: doctrine.orm.default_entity_manager

    cerad_game.game_repository.doctrine:
        class:  Cerad\Bundle\GameBundle\Entity\GameRepository
        factory_service: 'cerad_game.entity_manager.doctrine'
        factory_method:  'getRepository'
        arguments:  
            - 'Cerad\Bundle\GameBundle\Entity\Game'
            
    cerad_game.game_repository:
        alias: cerad_game.game_repository.doctrine

# ============================================
# Imports
    cerad_game.schedule_ArbiterGamesWithSlots.import:
        class: Cerad\Bundle\GameBundle\Schedule\Import\ArbiterGamesWithSlotsImport
        arguments:
            - '@cerad_project.project_repository'
            - '@cerad_level.level_repository'
            - '@cerad_game.game_repository'
            
    cerad_game.twig_extension:
        class:  Cerad\Bundle\GameBundle\TwigExtension\GameExtension
        arguments:  
            - '@cerad_level.level_repository'
        tags:
            - { name: twig.extension }
            