parameters:

services:
      cerad_project__project_meta_repository:
        class:  Cerad\Bundle\ProjectBundle\EntityRepository\ProjectMetaRepository
        arguments:  
            - '%cerad_project__project_files%'

